const imgAPI = {
  avatar: [
    '/images/avatars/olmedo_herrera.png',
    '/images/avatars/mauro_ojjione.png',
    '/images/avatars/fernando_pavon.png',
    '/images/avatars/woo_james.png',
    '/images/avatars/alejandro.png',
    '/images/avatars/pp_girl5.svg',
    '/images/avatars/pp_girl.svg',
    '/images/avatars/pp_boy.svg',
    '/images/avatars/pp_boy2.svg',
    '/images/avatars/pp_boy3.svg',
    '/images/avatars/pp_boy4.svg',
    '/images/avatars/pp_boy5.svg'
  ],
  avatartestimonials: [
    '/images/avatars/olmedo_herrera.png',
    '/images/avatars/mauro_ojjione.png',
    '/images/avatars/fernando_pavon.png',
    '/images/avatars/woo_james.png',
    '/images/avatars/alejandro.png',
  ],
  photo: [
    'https://via.placeholder.com/675x900/e1ad92/ffffff',
    'https://via.placeholder.com/967x725/ea6d6d/ffffff',
    'https://via.placeholder.com/1280x849/ea6db7/ffffff',
    'https://via.placeholder.com/967x725/bb6dea/ffffff',
    'https://via.placeholder.com/1048x701/6d6fea/ffffff',
    'https://via.placeholder.com/1050x700/6dc0ea/ffffff',
    'https://via.placeholder.com/970x725/6deaa6/ffffff',
    'https://via.placeholder.com/1051x700/b8de27/ffffff',
    'https://via.placeholder.com/1051x701/de9f27/ffffff',
    'https://via.placeholder.com/1050x700/ef4545/ffffff',
    'https://via.placeholder.com/1050x700/ffc4c4/757575',
    'https://via.placeholder.com/640x447/fdffc4/757575',
    'https://via.placeholder.com/1280x851/c4ffd7/757575',
    'https://via.placeholder.com/640x425/c4cdff/757575',
  ],
  saas: [
    '/images/saas/DSC01633.jpg',
    '/images/saas/DSC00067.jpg',
    '/images/saas/DSC01649.jpg',
    '/images/saas/app-counter.png',
    '/images/saas/DSC01505.jpg',
    '/images/saas/DSC00084.jpg',
    '/images/saas/DSC03517.jpg',
    '/images/saas/desktop_illustration_3.png',    
    '/images/saas/foodHub-6.jpg',
    '/images/saas/settings.png',  
    '/images/saas/idea.png',
    '/images/saas/restaurant.png',
    '/images/arrowUp.png',
    '/images/time-is-money.png',
    '/images/customer.png',
    '/images/online-learning.png',
    '/images/whatsapp.png',
    '/images/digital.png',
  ]
};

export default imgAPI;
